apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcp-autocomplete
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: gcp-autocomplete
    spec:
      containers:
      - name: gcp-autocomplete
        image: alihhussain/azurepublic:autocompv5
        ports:
        - containerPort: 443
          name: app
        - containerPort: 80
          name: redirect 
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-autocomplete
spec:
  type: LoadBalancer
  ports:
    - name: app
      port: 443
    - name: redirect
      port: 80
  selector:
    app: gcp-autocomplete
